using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace LibTmux.Generators;

/// <summary>Emits the closed catalog of queryable tmux format fields.</summary>
/// <remarks>
/// The catalog is generated rather than hand-written so the query vocabulary
/// stays closed: a field absent here cannot be translated, which is what makes
/// translate-or-throw enforceable instead of advisory.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class FieldCatalogGenerator : IIncrementalGenerator
{
    /// <summary>The closed catalog, and where each field lives on its entity.</summary>
    /// <remarks>
    /// Wire name and property are declared explicitly because the mapping is
    /// not systematic (<c>client_control</c> → <c>IsControlClient</c>, and two
    /// fields have no property at all).
    /// </remarks>
    private static readonly (
        string WireName,
        string Target,
        string Kind,
        bool Relation,
        string? Property)[] Fields =
    {
        ("client_control", "Client", "Boolean", false, "IsControlClient"),
        ("client_id", "Client", "TypedId", false, null),
        ("client_name", "Client", "String", false, "Name"),
        ("pane_command", "Pane", "String", false, null),
        ("pane_id", "Pane", "TypedId", false, "Id"),
        ("session_attached", "Session", "Boolean", false, "Attached"),
        ("session_id", "Session", "TypedId", false, "Id"),
        ("session_name", "Session", "String", false, "Name"),
        ("session_windows", "Session", "Int64", true, "Windows"),
        ("window_id", "Window", "TypedId", false, "Id"),
        ("window_name", "Window", "String", false, "Name"),
        ("window_panes", "Window", "Int64", true, "Panes"),
    };

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context) =>
        context.RegisterPostInitializationOutput(static registration =>
            registration.AddSource(
                "QueryFieldCatalog.g.cs",
                SourceText.From(Render(), Encoding.UTF8)));

    private static string Render()
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("namespace LibTmux.Query;");
        source.AppendLine();
        source.AppendLine("internal static partial class QueryFieldCatalog");
        source.AppendLine("{");
        source.AppendLine(
            "    internal static bool IsRelation(string wireName) => wireName switch");
        source.AppendLine("    {");
        foreach ((string wireName, _, _, bool relation, _) in Fields)
        {
            if (relation)
            {
                source.AppendLine($"        \"{wireName}\" => true,");
            }
        }

        source.AppendLine("        _ => false,");
        source.AppendLine("    };");
        source.AppendLine();
        source.AppendLine(
            "    internal static bool TryGetTarget(string wireName, out QueryTarget target)");
        source.AppendLine("    {");
        source.AppendLine("        switch (wireName)");
        source.AppendLine("        {");
        foreach ((string wireName, string target, _, _, _) in Fields)
        {
            source.AppendLine($"            case \"{wireName}\":");
            source.AppendLine($"                target = QueryTarget.{target};");
            source.AppendLine("                return true;");
        }

        source.AppendLine("            default:");
        source.AppendLine("                target = default;");
        source.AppendLine("                return false;");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine(
            "    internal static bool TryGetKind(string wireName, out QueryValueKind kind)");
        source.AppendLine("    {");
        source.AppendLine("        switch (wireName)");
        source.AppendLine("        {");
        foreach ((string wireName, _, string kind, _, _) in Fields)
        {
            source.AppendLine($"            case \"{wireName}\":");
            source.AppendLine($"                kind = QueryValueKind.{kind};");
            source.AppendLine("                return true;");
        }

        source.AppendLine("            default:");
        source.AppendLine("                kind = default;");
        source.AppendLine("                return false;");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine(
            "    internal static bool TryGetWireName(global::System.Type owner, string property, "
            + "out string wireName)");
        source.AppendLine("    {");
        foreach ((string wireName, string target, _, _, string? property) in Fields)
        {
            if (property is null)
            {
                continue;
            }

            source.AppendLine(
                $"        if (owner == typeof(global::LibTmux.{target}) "
                + $"&& property == \"{property}\")");
            source.AppendLine("        {");
            source.AppendLine($"            wireName = \"{wireName}\";");
            source.AppendLine("            return true;");
            source.AppendLine("        }");
        }

        source.AppendLine("        wireName = string.Empty;");
        source.AppendLine("        return false;");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine(
            "    internal static bool TryGetProperty(global::System.Type owner, string wireName, "
            + "out string property)");
        source.AppendLine("    {");
        foreach ((string wireName, string target, _, _, string? property) in Fields)
        {
            if (property is null)
            {
                continue;
            }

            source.AppendLine(
                $"        if (owner == typeof(global::LibTmux.{target}) "
                + $"&& wireName == \"{wireName}\")");
            source.AppendLine("        {");
            source.AppendLine($"            property = \"{property}\";");
            source.AppendLine("            return true;");
            source.AppendLine("        }");
        }

        source.AppendLine("        property = string.Empty;");
        source.AppendLine("        return false;");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine(
            "    internal static bool TryBindEntityScalar(global::System.Type owner, "
            + "string wireName, out QueryFieldAccessor accessor)");
        source.AppendLine("    {");
        foreach ((string wireName, string target, string kind, bool relation, string? property) in Fields)
        {
            if (property is null)
            {
                continue;
            }

            string read = relation
                ? $"checked((long)((global::LibTmux.{target})element).{property}.Count)"
                : kind switch
                {
                    "Boolean" => $"(bool)((global::LibTmux.{target})element).{property}",
                    "String" => $"(string)((global::LibTmux.{target})element).{property}",
                    "TypedId" =>
                        $"(global::LibTmux.{target}Id)((global::LibTmux.{target})element).{property}",
                    _ => $"((global::LibTmux.{target})element).{property}",
                };
            string valueType = relation
                ? "typeof(long)"
                : kind switch
                {
                    "Boolean" => "typeof(bool)",
                    "String" => "typeof(string)",
                    "TypedId" => $"typeof(global::LibTmux.{target}Id)",
                    _ =>
                        $"typeof(global::LibTmux.{target}).GetProperty(\"{property}\")!.PropertyType",
                };

            source.AppendLine(
                $"        if (owner == typeof(global::LibTmux.{target}) "
                + $"&& wireName == \"{wireName}\")");
            source.AppendLine("        {");
            source.AppendLine(
                "            accessor = new QueryFieldAccessor("
                + $"static element => {read}, {valueType});");
            source.AppendLine("            return true;");
            source.AppendLine("        }");
        }

        source.AppendLine("        accessor = null!;");
        source.AppendLine("        return false;");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine(
            "    internal static bool TryBindEntityRelation(global::System.Type owner, "
            + "string wireName, out QueryFieldAccessor accessor)");
        source.AppendLine("    {");
        foreach ((string wireName, string target, _, bool relation, string? property) in Fields)
        {
            if (!relation || property is null)
            {
                continue;
            }

            string child = wireName switch
            {
                "session_windows" => "Window",
                "window_panes" => "Pane",
                _ => throw new System.InvalidOperationException(
                    $"Unknown relation field '{wireName}'."),
            };
            source.AppendLine(
                $"        if (owner == typeof(global::LibTmux.{target}) "
                + $"&& wireName == \"{wireName}\")");
            source.AppendLine("        {");
            source.AppendLine(
                "            accessor = new QueryFieldAccessor("
                + $"static element => (global::LibTmux.CapturedRelation<global::LibTmux.{child}>)"
                + $"((global::LibTmux.{target})element).{property}, "
                + $"typeof(global::LibTmux.CapturedRelation<global::LibTmux.{child}>));");
            source.AppendLine("            return true;");
            source.AppendLine("        }");
        }

        source.AppendLine("        accessor = null!;");
        source.AppendLine("        return false;");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    internal static IReadOnlyList<string> WireNames { get; } =");
        source.AppendLine("    [");
        foreach ((string wireName, _, _, _, _) in Fields)
        {
            source.AppendLine($"        \"{wireName}\",");
        }

        source.AppendLine("    ];");
        source.AppendLine("}");
        return source.ToString();
    }
}
