using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace LibTmux.Generators;

/// <summary>Emits the closed catalog of queryable tmux format fields.</summary>
/// <remarks>
/// The catalog is generated rather than hand-written so the query vocabulary
/// stays closed: a field absent here cannot be translated, which is what makes
/// translate-or-throw enforceable instead of advisory.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class FieldCatalogGenerator : IIncrementalGenerator
{
    /// <summary>The closed catalog, and where each field lives on its entity.</summary>
    /// <remarks>
    /// Wire name and property are declared explicitly because the mapping is
    /// not systematic (<c>client_control_mode</c> → <c>IsControlClient</c>, and two
    /// fields have no property at all).
    /// </remarks>
    private static readonly (string WireName, string Target, bool Relation, string? Property)[]
        Fields =
    {
        ("client_control_mode", "Client", false, "IsControlClient"),
        ("client_id", "Client", false, null),
        ("client_name", "Client", false, "Name"),
        ("pane_command", "Pane", false, null),
        ("pane_id", "Pane", false, "Id"),
        ("session_attached", "Session", false, "Attached"),
        ("session_id", "Session", false, "Id"),
        ("session_name", "Session", false, "Name"),
        ("session_windows", "Session", true, "Windows"),
        ("window_id", "Window", false, "Id"),
        ("window_name", "Window", false, "Name"),
        ("window_panes", "Window", true, "Panes"),
    };

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context) =>
        context.RegisterPostInitializationOutput(static registration =>
            registration.AddSource(
                "QueryFieldCatalog.g.cs",
                SourceText.From(Render(), Encoding.UTF8)));

    private static string Render()
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("namespace LibTmux.Query;");
        source.AppendLine();
        source.AppendLine("internal static partial class QueryFieldCatalog");
        source.AppendLine("{");
        source.AppendLine(
            "    internal static bool IsRelation(string wireName) => wireName switch");
        source.AppendLine("    {");
        foreach ((string wireName, _, bool relation, _) in Fields)
        {
            if (relation)
            {
                source.AppendLine($"        \"{wireName}\" => true,");
            }
        }

        source.AppendLine("        _ => false,");
        source.AppendLine("    };");
        source.AppendLine();
        source.AppendLine(
            "    internal static bool TryGetTarget(string wireName, out QueryTarget target)");
        source.AppendLine("    {");
        source.AppendLine("        switch (wireName)");
        source.AppendLine("        {");
        foreach ((string wireName, string target, _, _) in Fields)
        {
            source.AppendLine($"            case \"{wireName}\":");
            source.AppendLine($"                target = QueryTarget.{target};");
            source.AppendLine("                return true;");
        }

        source.AppendLine("            default:");
        source.AppendLine("                target = default;");
        source.AppendLine("                return false;");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine(
            "    internal static bool TryGetWireName(string owner, string property, "
            + "out string wireName)");
        source.AppendLine("    {");
        source.AppendLine("        switch (owner + \".\" + property)");
        source.AppendLine("        {");
        foreach ((string wireName, string target, _, string? property) in Fields)
        {
            if (property is null)
            {
                continue;
            }

            source.AppendLine($"            case \"{target}.{property}\":");
            source.AppendLine($"                wireName = \"{wireName}\";");
            source.AppendLine("                return true;");
        }

        source.AppendLine("            default:");
        source.AppendLine("                wireName = string.Empty;");
        source.AppendLine("                return false;");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine(
            "    internal static bool TryGetProperty(string owner, string wireName, "
            + "out string property)");
        source.AppendLine("    {");
        source.AppendLine("        switch (owner + \".\" + wireName)");
        source.AppendLine("        {");
        foreach ((string wireName, string target, _, string? property) in Fields)
        {
            if (property is null)
            {
                continue;
            }

            source.AppendLine($"            case \"{target}.{wireName}\":");
            source.AppendLine($"                property = \"{property}\";");
            source.AppendLine("                return true;");
        }

        source.AppendLine("            default:");
        source.AppendLine("                property = string.Empty;");
        source.AppendLine("                return false;");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    internal static IReadOnlyList<string> WireNames { get; } =");
        source.AppendLine("    [");
        foreach ((string wireName, _, _, _) in Fields)
        {
            source.AppendLine($"        \"{wireName}\",");
        }

        source.AppendLine("    ];");
        source.AppendLine("}");
        return source.ToString();
    }
}
