"""Render the approved C# API Markdown from its canonical JSON contract."""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
import typing as t

DOCUMENT_ROOT = pathlib.Path(__file__).parents[2] / "docs"
API_PATH = DOCUMENT_ROOT / "public-api.json"
MARKDOWN_PATH = DOCUMENT_ROOT / "public-api.md"


def load_contract(path: pathlib.Path = API_PATH) -> dict[str, t.Any]:
    """Load the canonical public API contract.

    Parameters
    ----------
    path : pathlib.Path
        Contract path.

    Returns
    -------
    dict[str, typing.Any]
        Parsed contract.

    Examples
    --------
    >>> load_contract()["schema"]
    'libtmux-public-api'
    """
    with path.open(encoding="utf-8") as file_handle:
        return t.cast(dict[str, t.Any], json.load(file_handle))


def table_cell(value: object) -> str:
    r"""Escape one compact Markdown table cell.

    Parameters
    ----------
    value : object
        Cell value.

    Returns
    -------
    str
        Escaped single-line text.

    Examples
    --------
    >>> table_cell("a|b\nc")
    'a\\|b c'
    """
    return str(value).replace("|", r"\|").replace("\n", " ")


def code_span(value: object) -> str:
    """Wrap one value in a CommonMark code span.

    Parameters
    ----------
    value : object
        Code value.

    Returns
    -------
    str
        A code span whose delimiter does not collide with the value.

    Examples
    --------
    >>> code_span("CapturedRelation`1")
    '``CapturedRelation`1``'
    """
    text = table_cell(value)
    delimiter = "``" if "`" in text else "`"
    return f"{delimiter}{text}{delimiter}"


def sentence(label: str, value: object) -> str:
    """Render one labeled contract fact as a sentence.

    Examples
    --------
    >>> sentence("Equality", "generation and ID")
    'Equality: generation and ID.'
    """
    rendered = table_cell(value).rstrip(".")
    return f"{label}: {rendered}."


def render_type_contract(entry: dict[str, t.Any]) -> str:
    """Render review-critical type metadata in one table cell.

    Examples
    --------
    >>> render_type_contract({"summary": "Value.", "validation": "positive"})
    'Value. Validation: positive.'
    """
    facts = [str(entry.get("summary", "")).strip()]
    labels = {
        "equality": "Equality",
        "validation": "Validation",
        "behavior": "Behavior",
        "endpointPrecedence": "Endpoint precedence",
        "identity": "Identity",
        "defaultValue": "Default value",
    }
    for key, label in labels.items():
        value = entry.get(key)
        if value is None:
            continue
        if isinstance(value, dict):
            value = json.dumps(value, sort_keys=True, separators=(",", ":"))
        elif isinstance(value, list):
            value = ", ".join(str(item) for item in value)
        facts.append(sentence(label, value))
    state = entry.get("state", [])
    if state:
        facts.append(sentence("State", ", ".join(state)))
    return " ".join(fact for fact in facts if fact)


def render_member_notes(entry: dict[str, t.Any]) -> str:
    """Render review-critical member metadata in one table cell.

    Examples
    --------
    >>> render_member_notes({"summary": "Value.", "value": 0})
    'Value. Value: `0`.'
    """
    facts = [str(entry.get("summary", "")).strip()]
    if entry.get("compilerGenerated"):
        facts.append("Compiler-generated by the record struct.")
    if "value" in entry:
        facts.append(f"Value: {code_span(entry['value'])}.")
    labels = {
        "behavior": "Behavior",
        "failureMapping": "Failure mapping",
        "validation": "Validation",
        "listErrorPolicy": "List error policy",
        "missingBehavior": "Missing behavior",
        "optionCardinality": "Option cardinality",
    }
    for key, label in labels.items():
        if key in entry:
            value = entry[key]
            if isinstance(value, (dict, list)):
                value = json.dumps(value, sort_keys=True, separators=(",", ":"))
            facts.append(sentence(label, value))
    return " ".join(fact for fact in facts if fact)


def render_declaration(entry: dict[str, t.Any]) -> str:
    """Render a source-form declaration including the static modifier.

    Examples
    --------
    >>> render_declaration({"signature": "int Example.Get()", "static": True})
    'static int Example.Get()'
    """
    if entry.get("kind") == "enum value":
        return f"{entry['name']} = {entry['value']}"
    prefix = "static " if entry.get("static") else ""
    return f"{prefix}{entry['signature']}"


def render_platform(entry: dict[str, t.Any]) -> str:
    """Render the platform contract for one member.

    Examples
    --------
    >>> render_platform({"portable": True})
    'Portable'
    """
    annotations = entry.get("platformAnnotations", [])
    if annotations:
        return ", ".join(code_span(annotation) for annotation in annotations)
    return "Portable" if entry.get("portable") else "None"


def render_examples(examples: dict[str, dict[str, str]]) -> list[str]:
    """Return consumer-first examples using only approved members.

    Returns
    -------
    list[str]
        Markdown lines.

    Examples
    --------
    >>> render_examples(load_contract()["examples"])[0]
    '## Consumer-first examples'
    """
    lines = ["## Consumer-first examples", ""]
    for example in examples.values():
        lines.extend(
            [
                f"### {example['title']}",
                "",
                example["description"],
                "",
                "```csharp",
                *example["source"].splitlines(),
                "```",
                "",
            ]
        )
    return lines


def render(contract: dict[str, t.Any]) -> str:
    """Render deterministic Markdown from a canonical contract.

    Parameters
    ----------
    contract : dict[str, typing.Any]
        Parsed API contract.

    Returns
    -------
    str
        GitHub-flavored Markdown.

    Examples
    --------
    >>> render(load_contract()).startswith("# LibTmux approved public API")
    True
    """
    required = ", ".join(contract["supportedTmuxVersions"]["required"])
    minimum = contract["supportedTmuxVersions"]["minimum"]
    version_type = next(
        entry for entry in contract["types"] if entry["id"] == "T:LibTmux.TmuxVersion"
    )
    version_contract = version_type["versionContract"]
    lines = [
        "# LibTmux approved public API",
        "",
        "> This is a reviewed contract. Production implementation and passing",
        "> evidence are intentionally absent at this boundary.",
        "",
        (
            "The API targets `net8.0` and `net10.0`. Stable tmux releases from "
            f"`{minimum}` onward are supported."
        ),
        "The required compatibility matrix covers",
        (
            f"{required}; tmux master is advisory and "
            f"`{contract['supportedTmuxVersions']['advisoryStatus']}`."
        ),
        "Native Windows tmux execution is unsupported. IDs, snapshots, local query",
        "evaluation, JSON, and pure test helpers remain portable.",
        "",
        "Member IDs use the project-stable `libtmux-csharp-contract-v1` grammar;",
        "they are not compiler XML documentation IDs. The grammar retains C# source",
        "aliases, nullable markers, dotted explicit-interface names, and `()` for",
        "zero-argument methods.",
        "",
        "## TmuxVersion semantic contract",
        "",
        (
            "Minimum support is `3.2a` inclusive; `3.7b` is informational, "
            "not a support ceiling."
        ),
        "Stable releases use named capability intervals.",
        "The detection line starts with the exact lowercase prefix `tmux `.",
        "The complete parsing, ordering, detection, and support contract follows.",
        "",
        "```json",
        *json.dumps(version_contract, indent=2, ensure_ascii=False).splitlines(),
        "```",
        "",
        "## Packages",
        "",
        "| Package | Dependency | Responsibility |",
        "| --- | --- | --- |",
    ]
    lines.extend(
        (
            "| "
            + " | ".join(
                (
                    code_span(package["id"]),
                    table_cell(
                        ", ".join(
                            f"{dependency['id']} ({dependency['version']})"
                            for dependency in package["dependencies"]
                        )
                        or "None"
                    ),
                    table_cell(package["owns"]),
                )
            )
            + " |"
        )
        for package in contract["packages"]
    )
    lines.extend(
        ["", "## Conventions", "", "| Contract | Approved behavior |", "| --- | --- |"]
    )
    for name, value in contract["conventions"].items():
        lines.append(f"| {code_span(name)} | {table_cell(value)} |")
    lines.extend(["", *render_examples(contract["examples"])])

    public_types = [
        entry for entry in contract["types"] if "public" in entry["modifiers"]
    ]
    lines.extend(
        [
            "## Public types",
            "",
            (
                "| Type | Kind | Modifiers | Interfaces | Base | Ownership | "
                "Contract | Package |"
            ),
            "| --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    lines.extend(
        (
            "| "
            + " | ".join(
                (
                    code_span(entry["id"]),
                    table_cell(entry["kind"]),
                    code_span(", ".join(entry["modifiers"])),
                    (
                        ", ".join(code_span(item) for item in entry["interfaces"])
                        or "None"
                    ),
                    code_span(entry["baseType"]),
                    table_cell(entry["ownership"]),
                    table_cell(render_type_contract(entry)),
                    code_span(entry["package"]),
                )
            )
            + " |"
        )
        for entry in public_types
    )

    public_members = [
        entry
        for entry in contract["members"]
        if entry["visibility"] in {"public", "explicit"} and entry["kind"] != "type"
    ]
    grouped: dict[str, list[dict[str, t.Any]]] = {}
    for member in public_members:
        grouped.setdefault(member["declaringType"], []).append(member)
    lines.extend(["", "## Public members", ""])
    for declaring_type in sorted(grouped):
        lines.extend(
            [
                f"### {code_span(declaring_type)}",
                "",
                (
                    "| Member ID | Declaration | Visibility | Static | Platform | "
                    "Notes |"
                ),
                "| --- | --- | --- | --- | --- | --- |",
            ]
        )
        for member in sorted(grouped[declaring_type], key=lambda item: item["id"]):
            member_id = code_span(member["id"])
            declaration = code_span(render_declaration(member))
            visibility = (
                "Explicit interface" if member["visibility"] == "explicit" else "Public"
            )
            if member.get("kind") == "enum value":
                static = "Implicit"
            else:
                static = "Yes" if member.get("static") else "No"
            platform = render_platform(member)
            notes = render_member_notes(member)
            lines.append(
                f"| {member_id} | {declaration} | {visibility} | {static} | "
                f"{platform} | {table_cell(notes)} |"
            )
        lines.append("")

    lines.extend(
        [
            "## Query boundary",
            "",
            "`Matching()` consumes `IEnumerable<T>` and produces `IReadOnlyList<T>`.",
            "The only Python-style edge lookup is `name__contains`. Cardinality uses",
            "the BCL names `First`, `FirstOrDefault`, `Single`, `SingleOrDefault`,",
            (
                "`Any`, and `Count`. Safe planning and physical tmux mappings stay "
                "internal;"
            ),
            "`UnsafeTmuxFilter` is the explicit native-semantics escape hatch.",
            "",
            "## Ownership boundary",
            "",
            (
                "`Server`, `Session`, `Window`, `Pane`, and `Client` are borrowed "
                "immutable"
            ),
            "handles and never perform destructive disposal. Only clearly named owned",
            "or temporary scopes implement `IAsyncDisposable`. Cleanup is bounded,",
            "idempotent, and its failures remain observable.",
            "",
        ]
    )
    internal_types = [
        entry for entry in contract["types"] if "internal" in entry["modifiers"]
    ]
    internal_members = [
        entry
        for entry in contract["members"]
        if entry["visibility"] == "internal" and entry["kind"] != "type"
    ]
    lines.extend(
        [
            "## Approved internal implementation contract",
            "",
            "These internal types and members are frozen because parity rows and",
            "component ownership depend on their exact typed boundaries.",
            "",
            "| Type | Kind | Contract |",
            "| --- | --- | --- |",
        ]
    )
    lines.extend(
        f"| {code_span(entry['id'])} | {table_cell(entry['kind'])} | "
        f"{table_cell(render_type_contract(entry))} |"
        for entry in internal_types
    )
    lines.extend(
        [
            "",
            "| Member ID | Declaration | Notes |",
            "| --- | --- | --- |",
        ]
    )
    lines.extend(
        f"| {code_span(entry['id'])} | {code_span(render_declaration(entry))} | "
        f"{table_cell(render_member_notes(entry))} |"
        for entry in internal_members
    )
    lines.append("")
    return "\n".join(lines)


def write_or_check(*, check: bool) -> bool:
    """Write the rendered appendix or verify the checked-in output.

    Parameters
    ----------
    check : bool
        Compare without writing when true.

    Returns
    -------
    bool
        Whether the requested operation succeeded.

    Examples
    --------
    >>> isinstance(write_or_check(check=True), bool)
    True
    """
    expected = render(load_contract())
    if check:
        return (
            MARKDOWN_PATH.is_file()
            and MARKDOWN_PATH.read_text(encoding="utf-8") == expected
        )
    MARKDOWN_PATH.write_text(expected, encoding="utf-8")
    return True


def main(argv: list[str] | None = None) -> int:
    """Render or check the approved API appendix.

    Parameters
    ----------
    argv : list[str] | None
        Optional command arguments.

    Returns
    -------
    int
        Process exit code.

    Examples
    --------
    >>> main(["--check"])
    0
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    if write_or_check(check=arguments.check):
        return 0
    print("public-api.md differs from public-api.json", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
